sudo: required
dist: trusty
language: minimal
services:
  - docker

# before_install:
#   - sudo apt-get install -y python-pip
#   - sudo -H pip2 install docker

env:
  global:
    - ROS_REPO=ros
    - ADDITIONAL_DEBS=python-docker
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
