sudo: required
dist: trusty
language: minimal
services:
  - docker

env:
  global:
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO="indigo"
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="melodic"
matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo"
    - env: ROS_DISTRO="melodic"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
